controllers:
    resource: ../src/Controller/
    type: annotation

homepage:
    path: /
    controller: App\Controller\HomepageController::preview

Catalog:
    path: /Catalog
    controller: App\Controller\CatalogController::index

Database&Doctrine:
    path: /Database&Doctrine
    controller: App\Controller\DatabaseDoctrineController::index

Use&HTTPClient:
    path: /HTTPClient
    controller: App\Controller\UseHttpClientController::index

symfony_desc_get:
    path: /symfonydesc
    controller: App\Controller\SymfonyDescriptionController::getSymfonyDesc

symfony_desc_create:
    path: /symfonydesc?{header}&{description}
    controller: App\Controller\SymfonyDescriptionController::createSymfonyDesc

kernel:
    resource: ../src/Kernel.php
    type: annotation
